// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using PicoNet.Infrastructure.Data;

#nullable disable

namespace PicoNet.Infrastructure.Migrations
{
    [DbContext(typeof(PicoNetDbContext))]
    [Migration("20260522153852_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PicoNet.Domain.Entities.ShortenedUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedDomains")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Campaign")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("ClickCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomAlias")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxClicks")
                        .HasColumnType("integer");

                    b.Property<string>("NanoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NanoId");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(\"OriginalUrl\", '') || ' ' || coalesce(\"CustomAlias\", '') || ' ' || coalesce(\"Tags\", ''))", true);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_shortened_urls_created_at");

                    b.HasIndex("CustomAlias")
                        .IsUnique()
                        .HasDatabaseName("IX_shortened_urls_custom_alias")
                        .HasFilter("\"CustomAlias\" IS NOT NULL");

                    b.HasIndex("ExpiryTime")
                        .HasDatabaseName("IX_shortened_urls_expiry_time");

                    b.HasIndex("NanoId")
                        .IsUnique()
                        .HasDatabaseName("IX_shortened_urls_nano_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("IX_shortened_urls_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_shortened_urls_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_shortened_urls_user_id");

                    b.HasIndex("UserId", "Status", "IsDeleted")
                        .HasDatabaseName("IX_shortened_urls_user_status_deleted");

                    b.ToTable("ShortenedUrls", (string)null);
                });

            modelBuilder.Entity("PicoNet.Domain.Entities.UrlVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("ShortenedUrlId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("VisitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_url_visits_country");

                    b.HasIndex("ShortenedUrlId")
                        .HasDatabaseName("IX_url_visits_shortened_url_id");

                    b.HasIndex("VisitedAt")
                        .HasDatabaseName("IX_url_visits_visited_at");

                    b.HasIndex("ShortenedUrlId", "VisitedAt")
                        .HasDatabaseName("IX_url_visits_url_visited");

                    b.ToTable("UrlVisits", (string)null);
                });

            modelBuilder.Entity("PicoNet.Domain.Entities.UrlVisit", b =>
                {
                    b.HasOne("PicoNet.Domain.Entities.ShortenedUrl", "ShortenedUrl")
                        .WithMany("Visits")
                        .HasForeignKey("ShortenedUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortenedUrl");
                });

            modelBuilder.Entity("PicoNet.Domain.Entities.ShortenedUrl", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
